#!/usr/bin/env bash
#set -x
source "${HOME}/.BASH_ENV"
if [[ "$1" == "-c" || "$1" == "--clip" ]]
then
    TOCLIP=true
    shift
elif [[ "$1" == "-t" || "$1" == "--type" ]]
then
    TYPE=true
    shift
fi

SEARCH="$1"
shift

if [[ "${SEARCH}" == "-" ]]
then
    SEARCH=''
fi

passfile=$(pass-file-chooser "${SEARCH}")

if [[ -n ${passfile} ]]; then
    if [[ "$@" == "" || $1 == -* ]]; then
        cmd=show
    else
        cmd=$1
        shift
    fi
    if [[ "${TOCLIP}" == "true" || "${SCRIPTNAME}" == "fassc" ]]
    then
        # Copy to the clipboard (auto clean in 45 seconds)
        nohup pass ${cmd} "${@}" "${passfile}" --clip &>/dev/null &
    	echo "Copied requested data of ${passfile} to clipboard. The will be discarded from the clipboard in a minute or so"
    else
        RESULT=$(pass ${cmd} "${@}" "${passfile}")
        if [[ "${TYPE}" == "true" ]]
        then
            type-command --check-availability || exit 1
            # Send the result to the keyboard buffer
            nohup type-command "${RESULT}" &>/dev/null &
        else
            echo "${RESULT}"
        fi
    fi
fi
