#!/usr/bin/env bash
#set -x
source "${HOME}/.BASH_ENV"
if [[ "$1" == "-c" || "$1" == "--clip" ]]
then
    TOCLIP=true
    shift
elif [[ "$1" == "-t" || "$1" == "--type" ]]
then
    TYPE=true
    shift
else
    if [[ $(basename "$0") == "fassc" ]]; then
        TOCLIP=true
    fi
fi

SEARCH="$1"
shift

if [[ "${SEARCH}" == "-" ]]
then
    SEARCH=''
fi

# Choose the pass-file
passfile=$(pass-file-chooser "${SEARCH}")

if [[ -n ${passfile} ]]; then
    if [[ "$@" == "" || $1 == -* ]]; then
        cmd=show
    else
        cmd=$1
        shift
    fi
    # if invoked via fassc symlink then send result to clipboard
    if [[ "${TOCLIP}" == "true" ]]
    then
        # Copy requested data to the clipboard (auto clean in 45 seconds)
        nohup pass ${cmd} "${@}" "${passfile}" --clip &>/dev/null &
    	echo "Copied requested data from the ${passfile} to clipboard. The copied data will be discarded from the clipboard in a minute or so"
    else
        # Get the data
        RESULT=$(pass ${cmd} "${@}" "${passfile}")
        if [[ "${TYPE}" == "true" ]]
        then
            # Send the result to the keyboard buffer (e.g. type URL in the browser's search bar
            nohup type-command "${RESULT}" &>/dev/null &
        else
            # Send the result to the stdout
            echo "${RESULT}"
        fi
    fi
fi
