#!/usr/bin/env bash
#set -x
PREFIX="${PASSWORD_STORE_DIR:-$HOME/.password-store}"
PREFIX="${PREFIX%/}"
SED_IT="sed -e s:${PREFIX}/:: -e s/\.gpg$//"

: ${GUI_CHOOSER:=true}
: ${CHOOSER_NUM_LINES:=25}
: ${CHOOSER_PROMPT:=Choose password entry}

CHOOSER_SEARCH="$1"
shift

if [[ "${CHOOSER_SEARCH}" == "-" ]]
then
    CHOOSER_SEARCH=''
fi

declare -a found

while read -r ; do
    found[${#found[@]}]=${REPLY}
done < <(find "$PREFIX" -type f ! -regex "${PREFIX}/\..*" -ipath "*${CHOOSER_SEARCH}*" | ${SED_IT})

if [[ ${#found[@]} = 0 ]]
then
    exit
elif [[ ${#found[@]} = 1 ]]; then
    echo "${found[0]}"
    exit
fi

export CHOOSER_SEARCH=\'${CHOOSER_SEARCH}
export GUI_CHOOSER
export CHOOSER_PROMPT

chooser "${found[@]}"
